---

- name: install supervisor
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - supervisor

- name: enable/start supervisor
  service: >
    name=supervisor
    state=running
    enabled=yes
