---
# setup nginx server

- name: add ppa:nginx/development
  apt_repository: repo='ppa:nginx/development'
  when: nginx_version_dev

- name: install nginx
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - nginx

- name: update nginx log directory
  file: >
    path="/var/log/nginx"
    mode=0755
    state=directory

- name: enable nginx
  service: name=nginx state=started enabled=yes
