---
# setup nginx server

- name: disable apache
  service: name=apache2 state=stopped enabled=no

- name: add ppa:nginx/development
  apt_repository: repo="{{ nginx_ppa }}"
  when: nginx_version_dev

- name: install nginx
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - nginx

- name: update access to nginx log directory
  file: >
    path="{{ nginx_log_path }}"
    mode=0755
    state=directory
