---

- name: stop webapp
  supervisorctl: name="{{ service_name }}:" state=stopped
  tags:
    - stop_webapp

- name: start webapp
  supervisorctl: name="{{ service_name }}:" state=restarted
  tags:
    - start_webapp
