---
# setup the django service in supervisor

- name: determine serivce user home
  shell: >
    getent passwd {{ service_user }} | cut -d: -f6
  changed_when: false
  register: service_user_home_output

- name: set fact service_user_home
  set_fact: >
    service_user_home="{{ service_user_home_output.stdout }}"

- name: create service log directory
  file: >
    path="{{ service_log_path }}"
    owner="{{ service_user }}"
    group="{{ service_group }}"
    mode=0755
    state=directory

- name: configure service in supervisor
  template: >
    src="service_group.conf.j2"
    dest="/etc/supervisor/conf.d/{{ service_name }}.conf"
    backup=yes
  notify:
    - supervisor reread
    - supervisor update
    - restart service group
