---
# setup nginx for gunicorn and static files

- name: remove nginx default site
  file: >
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify: restart nginx

- name: install self signed cartificate and key
  copy: >
    src="{{ item }}"
    dest="{{ ssl_path }}/{{ item }}"
    owner={{ service_user }}
    group={{ service_group }}
    mode=0644
  with_items:
    - "server.key"
    - "server.crt"

- name: configure nginx django/gunicorn site
  template: >
    src="nginx.conf.j2"
    dest="/etc/nginx/sites-available/{{ service_name }}.conf"
    owner={{ service_user }}
    group={{ service_group }}
    mode=0644
    backup=yes
  notify: restart nginx

- name: enable nginx django/gunicorn site
  file: >
    src="/etc/nginx/sites-available/{{ service_name }}.conf"
    dest="/etc/nginx/sites-enabled/{{ service_name }}.conf"
    state=link
  notify: restart nginx
