---
# setup postgresql server

- name: install postgresql
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - postgresql-9.3
    - postgresql-contrib-9.3
    - libpq-dev
    - python-psycopg2

- name: enable postgresql
  service: name=postgresql state=started enabled=yes
