---
# create a new django project or link the existing to the install_path

- name: register source_path_service variable
  stat: >
    path="{{ source_path }}/{{ service_name }}"
  register: source_path_service

- include: 11-startproject.yml
  when: source_path_service.stat.exists == False

- name: link django project from /vagrant dir
  file: >
    src={{ source_path }}
    dest={{ install_path }}
    owner={{ service_user }}
    group={{ service_group }}
    state=link
  notify:
    - restart service group
