---
# choose python version and setup a service virtualenv

- include: 22-python2.yml
  when: not use_python3

- include: 23-python3.yml
  when: use_python3

- name: update virtualenv owner
  file: >
    path={{ venvs_path }}
    owner={{ service_user }}
    group={{ service_group }}
    recurse=yes

- name: configure virtualenv directory
  lineinfile: >
    dest=/etc/environment
    regexp=^WORKON_HOME={{ venvs_path }}
    line=WORKON_HOME={{ venvs_path }}
    state=present

- name: create postactivate
  template: >
    src=virtualenv/postactivate.j2
    dest={{ virtualenv_path }}/bin/postactivate
    owner={{ service_user }}
    group={{ service_user }}
    mode=0640

- name: enable virtualenv on login
  lineinfile: >
    dest="~{{ service_user }}/.bashrc"
    line="source {{ virtualenv_path }}/bin/activate"
    state=present
